import Link from "next/link";

// CHATGPT PROMPT TO GENERATE YOUR TERMS & SERVICES — replace with your own data 👇

// 1. Go to https://chat.openai.com/
// 2. Copy paste bellow
// 3. Replace the data with your own (if needed)
// 4. Paste the answer from ChatGPT directly in the <pre> tag below

// You are an excellent lawyer.

// I need your help to write a simple Terms & Services for my website. Here is some context:
// - Website: https://shipfa.st
// - Name: ShipFast
// - Contact information: marc@shipfa.st
// - Description: A JavaScript code boilerplate to help entrepreneurs launch their startups faster
// - Ownership: when buying a package, users can download code to create apps. They own the code but they do not have the right to resell it. They can ask for a full refund within 7 day after the purchase.
// - User data collected: name, email and payment information
// - Non-personal data collection: web cookies
// - Link to privacy-policy: https://shipfa.st/privacy-policy
// - Governing Law: France
// - Updates to the Terms: users will be updated by email

// Please write a simple Terms & Services for my site. Add the current date. Do not add or explain your reasoning. Answer:

const TOS = () => {
  const appName = "REMOVE BACKGROUND";
  return (
    <main className="max-w-xl mx-auto">
      <div className="p-5">
        <Link href="/" className="btn btn-ghost">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            className="w-5 h-5"
          >
            <path
              fillRule="evenodd"
              d="M15 10a.75.75 0 01-.75.75H7.612l2.158 1.96a.75.75 0 11-1.04 1.08l-3.5-3.25a.75.75 0 010-1.08l3.5-3.25a.75.75 0 111.04 1.08L7.612 9.25h6.638A.75.75 0 0115 10z"
              clipRule="evenodd"
            />
          </svg>
          Back
        </Link>
        <h1 className="text-3xl font-extrabold pb-6">
          Terms and Conditions for {appName}
        </h1>

        <pre
          className="leading-relaxed whitespace-pre-wrap"
          style={{ fontFamily: "sans-serif" }}
        >
          {`Last Updated: Aug 01, 2024

Terms and Services

Welcome to REMOVE BACKGROUND!

These Terms and Services ("Terms") govern your use of our website located at https://REMOVE BACKGROUND.pages.dev ("Website") and our services. By accessing or using our Website and services, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Website or services.

1. Services Description

REMOVE BACKGROUND is an AI-powered tool that converts users' images into claymation-style art. Users can upload images to be processed by our AI.

2. Ownership and Rights

When you request an image to be processed, you retain the right to download the resulting image generated by REMOVE BACKGROUND. However, by using our service, you grant us a non-exclusive, royalty-free, worldwide license to keep a copy of the generated image and use it for commercial purposes, including but not limited to displaying it on our Website, marketing, and promotional materials.

3. User Data Collection

We collect the images you upload for processing. We do not collect any other personal data. For more information, please review our Privacy Policy.

4. Non-Personal Data Collection

We do not collect any non-personal data.

5. Governing Law

These Terms are governed by and construed in accordance with the laws of the United States. Any disputes arising out of or related to these Terms will be resolved in accordance with the laws of the United States.

6. Contact Information

If you have any questions about these Terms, please contact us at hello@a1d.ai.

By using our Website and services, you acknowledge that you have read, understood, and agree to be bound by these Terms.

Thank you for using REMOVE BACKGROUND!`}
        </pre>
      </div>
    </main>
  );
};

export default TOS;